### ISSUE TITLE
Warning when calling `read` method of Stream class with 0 length

### ISSUE THREAD

**Issue by zyfran** [guzzle/psr7#119]
Hi.
I write API and I use behat to test it.
I'm getting `Warning: fread(): Length parameter must be greater than 0 in vendor/guzzlehttp/psr7/src/Stream.php line 211` for every response with empty body.

I made quick fix for that line like

``` php
return $length > 0 ? fread($this->stream, $length) : '';
```

PHP: 7.0.8
guzzlehttp/psr7: 1.3.1

**Comment by Tobion** [comment]
I agree that there is a problem. `\Psr\Http\Message\StreamInterface::read` should return a string or throw an exception. Both are not done because it causes a warning and returns `false` because `fread` returns false in this case. There are two solutions:

1. ignore length of 0 an return `''` as you suggested,
2. transform the warning to an exception.

**Comment by zyfran** [comment]
Thank you @Tobion 
Do I need to create merge request?

**Comment by Tobion** [comment]
Would be nice if you create a PR. When length === 0, return ''. And also check if fread returns false and throw an exception then. So a negative length will still fail.

**Comment by zyfran** [comment]
@Tobion Thank you
