### ISSUE TITLE
ServerRequest::fromGlobals extendable?

### ISSUE THREAD

**Issue by jackbentley** [guzzle/psr7#132]
I haven't tested. However, am I correct in saying that you can't extend `ServerRequest` and use `::fromGlobals` as it doesn't call `new static()` but rather `new ServerRequest()`.

If you were to use it, you would end up with a `ServerRequest` class when being called from a child class?

https://github.com/guzzle/psr7/blob/master/src/ServerRequest.php#L174
```php
$serverRequest = new ServerRequest($method, $uri, $headers, $body, $protocol, $_SERVER);
```

maybe should be:

```php
$serverRequest = new static($method, $uri, $headers, $body, $protocol, $_SERVER);
```

If this is the case, then maybe also all `self` usages should be using `static` instead?
E.g. https://github.com/guzzle/psr7/blob/master/src/ServerRequest.php#L170

**Comment by Tobion** [comment]
Yes you would get a `ServerRequest` class. But as long as there is not valid use-case for extending, there is also no point in use late static binding. I don't think ServerRequest should be extended because it's implementing a standard interface. So subclassing it to add custom logic will most likely not make it behave according to the interface. And if you just want to add custom helper methods, I'd recommend to put them in a different class.

**Comment by jackbentley** [comment]
The only reason I found it was because I was converting my existing HTTP request class into a PSR friendly class, using this library.

I ended up overriding the method for the mean-time.
