### ISSUE TITLE
Generate mime type list instead of manually maintaining it

### ISSUE THREAD

**Issue by sagikazarmark** [guzzle/psr7#195]

**Comment by Nyholm** [comment]
Would you care to elaborate? How would we generate one?

**Comment by sagikazarmark** [comment]
Instead of manual pull requests like #170 we could generate from the file linked in the [code](https://github.com/wbohlken/psr7/blob/b7ac0827659188f65b4724435c5319771d189511/src/functions.php#L631).

**Comment by prisis** [comment]
If you like just use this https://github.com/narrowspark/mimetypes, maybe as a composer suggest

**Comment by fruitl00p** [comment]
It seems the entire list (or at least the url mentioned) is *very* outdated... Thus updating it using the current list (https://github.com/apache/httpd/blob/trunk/docs/conf/mime.types) seems the only *real* way to go. I can imagine having this list 'hardcoded' in this repo, but atleast update it with the current list from Apache instead of an outdated 1.x release ;)

**Comment by gmponos** [comment]
Maybe use the one from symfony..

https://github.com/symfony/mime/blob/master/MimeTypes.php

 or inside the function check if the symfony/mime is installed to get it from there?

**Comment by Nyholm** [comment]
Im closing due inactivity. 

If you want to send a file that is not on the list, you have to provide your own headers.
