### ISSUE TITLE
Request class hardcoded in GuzzleHttp\Psr7\modify_request

### ISSUE THREAD

**Issue by adick** [guzzle/psr7#257]
I'm using an extended GuzzleHttp\Psr7\Request with the guzzle client: 

```
class FooRequest extends \GuzzleHttp\Psr7\Request {

}

$client = new Client(...);
$request = new FooRequest(...);
$response = $client->send($request);
```

The problem is, that `GuzzleHttp\Psr7\modify_request` creates a new `GuzzleHttp\Psr7\Request` instead of maintaining the class of the supplied instance.

The fix is very simple: 

In function `GuzzleHttp\Psr7\modify_request`, 

replace 
```
return new Request(
```

with
```
$requestClass = get_class($request);
return new $requestClass(
```
that way, a new instance of the correct class is created.

**Comment by sagikazarmark** [comment]
@adick PSR-7 classes are not supposed be extended.

To be more precise: `modify_request` accepts an object implementing PSR-7 Request and returns one implementing the same interface. That's the guarantee, nothing more.

Your proposed solution wouldn't work for all cases, because the constructor is not part of the interface, so you can easily define your own constructor with different parameters. In that case the proposed solution would just break.

Sorry, but this won't end up in the library for the above reasons.

**Comment by adick** [comment]
@sagikazarmark Thanks for the hint, I'll implement `Psr\Http\Message\RequestInterface` and map the response via mapResponse middleware instead of extending the Request.
