### ISSUE TITLE
_parse_message() in functions.php is not parsing message correctly

### ISSUE THREAD

**Issue by jakobhans** [guzzle/psr7#277]
I know the problem is in the regex used to split the message. I am getting this message:
```
"""
      HTTP/1.1 200 OK\r\n
      Content-ID: 797207\r\n
      Object-ID: 1\r\n
      Content-Description: Welcome to 1159 Hay 1, Bodega Bay!\r\n
      Content-Type: image/jpeg\r\n
      Location: https://mediall.rapmls.com/norcalmls/listingpics/bigphoto/2019/06/10/e9931d3a-7951-41bf-96e6-4545c8561a2f.jpg\r\n
"""
```
This is getting parsed as a single message part instead of using the first line as the header. I think the problem lies here:
https://github.com/guzzle/psr7/blob/868353eb117c202ee1f3b214eef9717e3d871297/src/functions.php#L770
Changing it this way worked for me but I don't know if it is correct to make a pull request:
```
$messageParts = preg_split("/\r?\n\r?\n?/", $message, 2);
```

**Comment by Tobion** [comment]
The message you try to parse is invalid. There must be an two new lines (an empty line) between headers and body. See https://tools.ietf.org/html/rfc7230#section-3

**Comment by jakobhans** [comment]
Thank you @Tobion . I suspected there was a problem with the response. Will address this correctly with my feed provider.

**Comment by jakobhans** [comment]
I was told by the support that:
> Per https://tools.ietf.org/html/rfc7230#section-3, an empty line indicates the end of the header section,
> and the start of an optional message body.  The given response is only comprised of the start-line and
> headers, there is no body.
Is this correct? Why am I getting the "Missing header delimiter" error if this is the case?

**Comment by jakobhans** [comment]
I see this commit from last year (https://github.com/guzzle/psr7/commit/82b46b9c60ce3f192baf933caad7387976452044#diff-84b928a9905378810b602c8a740b4cba) where the test for requests without a body was removed and some changes were made specifically to this function. Is this where my problem lies?

**Comment by sagikazarmark** [comment]
As per the RFC every header line must end with an empty line (CRLF) and the header section must be terminated with another which is not optional.

The mentioned commit was a security fix for a vulnerability in Apache related to folded headers.

**Comment by jakobhans** [comment]
I honestly don't see what the problem is, this is definitely a problem inside Guzzle since we do see the CRLF a the end of the stream... I just downgraded some packages to see if it works and if the version is 1.3.1 it does work perfectly. Will try to hunt down my particular problem and post here in a few days.

**Comment by Tobion** [comment]
It needs two line breaks at the end of the headers. One after the last header and one empty line.

**Comment by jakobhans** [comment]
I have been working on this and still having problems with the most recent version, the data had been coming perfectly fine, with he final empty line, all along. I was just dd()'ing in a point I shouldn't have done that. I'm just puzzled with why would the test for parsing headers without body be deleted. Have plans to work on this repo this weekend to see if there is a problem there.

**Comment by sagikazarmark** [comment]
@jakobhans the earlier version of the library tolerated that kind of RFC violation, but we had to close that hole because of a security problem.

I would like to emphasize again, that your stream must have **two line breaks** at the end (one after the last header, one as a header separator), even if there is no body. (Sorry if I'm stating the obvious, but I wasn't sure if this is clear) There are [tests](https://github.com/guzzle/psr7/blob/cec376c/tests/FunctionsTest.php#L285) proving this kind of behavior works.

If there is really a bug in Guzzle, the easiest way of proving that is a breaking test.

But looking at your proposed solution of changing the message split regex: that would remove the restriction for having two line breaks after the last header which would violate the RFC. It also tells me the problem might actually be with the invalid response.

**Comment by Tobion** [comment]
Closing as there is no further information.
