### ISSUE TITLE
Query escaping

### ISSUE THREAD

**Issue by red-led** [guzzle/psr7#366]
**Description**
`\GuzzleHttp\Psr7\Uri::withQueryValue(s)` does not handle `+` sign escaping;

**How to reproduce**
```php
$uri = \GuzzleHttp\Psr7\Uri::withQueryValue(
    new \GuzzleHttp\Psr7\Uri('test'),
    'date',
    '2021-01-11T17:50:00+03:00'
);
echo (string)$uri;
```
* Result: `test?date=2021-01-11T17:50:00+03:00`
* Expected result: `test?date=2021-01-11T17:50:00%2B03:00`

**Possible Solution**
Add `'+' => '%2B'` to `\GuzzleHttp\Psr7\Uri::$replaceQuery`?

**Additional context**
Also there is whole list of [reserved characters](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters), that must be percent-encoded.

**Comment by GrahamCampbell** [comment]
The encoding is simply done using `rawurlencode`, which claims to be encoding as of RFC 3986. If you think there is a bug there, PHP needs to fix this.

**Comment by nyamsprod** [comment]
@red-led , I think your bug report is incorrect because your expected result is incorrect. As noted in your link reserved character encoding is governed by the URI scheme and component.

In relation to PSR-7, the URI scheme by default is `http` and query string encoding should be done according to `RFC3986`. 

Furthermore,  PSR-7 states that you *MUST* not double encode characters in your component. 

the `+` character is only meaningful in the context of `RFC1738` query component which PSR-7 does not cover. Thus, your report is incorrect and Guzzle Uri implementation is correct to not encode the `+` sign in this context.

**Comment by GrahamCampbell** [comment]
Closing due to the discussion.
