### ISSUE TITLE
Fix for CVE-2022-24775 causes non-standard behavior; appears to break RFC-7230 compliance

### ISSUE THREAD

**Issue by cosmolux** [guzzle/psr7#524]
**PHP version**: 7.0.32 (affects all versions)

**Description**
The fix for CVE-2022-24775 causes an exception to be thrown when receiving HTTP headers with [unusual characters](https://github.com/guzzle/psr7/blob/bc778a3f18eb0f8423ea707cd0bdf375c696ec81/src/MessageTrait.php#L259-L264) in the value.  However, this is contradictory to [RFC-7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.4) which states:

> A user agent that receives an obs-fold in a response message that is not within a message/http container MUST replace each received obs-fold with one or more SP octets prior to interpreting the field value.

and

> A recipient SHOULD treat other octets in field content (obs-text) as opaque data.

[Comments in the source file](https://github.com/guzzle/psr7/blob/bc778a3f18eb0f8423ea707cd0bdf375c696ec81/src/MessageTrait.php#L254-L257) suggest confusion between Guzzle acting as a client vs as a sender.

**How to reproduce**
Create a script that sets a cookie with a decimal 1 octet in the value. (\x01 was found in the wild)
```php
<?php
header("Set-Cookie: 123\x01abc; path=/; Max-Age=900");
echo "Hello World\n";
```
Typical user-agents such as Firefox and curl accept the header...
```my-machine:~ my-dir$ curl -v  127.0.0.1:8000/ 
*   Trying 127.0.0.1:8000...
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Host: 127.0.0.1:8000
< Connection: close
< X-Powered-By: PHP/7.0.32
< Set-Cookie: 123abc; path=/; Max-Age=900
< Content-type: text/html; charset=UTF-8
< 
Hello World
* Closing connection 0
```
However, using recent versions of guzzle...
```php
<?php
require 'vendor/autoload.php';
$client = new GuzzleHttp\Client;
$response = $client->get('http://127.0.0.1:8000/');
echo $response->getHeader('Set-Cookie')[0];
echo $response->getBody();
```
... results in ...
```
Fatal error: Uncaught InvalidArgumentException: "123abc; path=/; Max-Age=900" is not valid header value in /guzzle_test/vendor/guzzlehttp/psr7/src/MessageTrait.php on line 267
```
**Possible Solution**
Revert to the previous behavior for header processing.

**Additional context**
This bug was filed because I am unable to use the latest guzzle because a major vendor sends data in headers that does not comply.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. The commit you link to was since changed. Is this issue still present on the very latest version of guzzle and its psr7 library?

**Comment by cosmolux** [comment]
Hi @GrahamCampbell , thanks for taking a look.  Yes, I have now switched to PHP 7.4 and was able to install guzzle 7.4.5 with psr7 2.4.0.  The exception remains, though the message source changed a little:
`Fatal error: Uncaught InvalidArgumentException: "123abc; path=/; Max-Age=900" is not valid header value in /radar/api/tests/pages/guzzle_test/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 173`

Would it be helpful if I update the ticket to reflect these changes?

**Comment by GrahamCampbell** [comment]
Thanks. That's all the information I need for now. I'll discuss it with the team.

**Comment by TimWolla** [comment]
> However, this is contradictory to [RFC-7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.4) which states:

RFC 7230 was obsolted by [9110](https://httpwg.org/specs/rfc9110.html).

> A user agent that receives an obs-fold in a response message that is not within a message/http container MUST replace each received obs-fold with one or more SP octets prior to interpreting the field value.

guzzle/psr7 indeed violates this MUST and the comment acknowledges that:

https://github.com/guzzle/psr7/blob/bc778a3f18eb0f8423ea707cd0bdf375c696ec81/src/MessageTrait.php#L259-L261

This is not relevant to the issue you are seeing, though, as you are not dealing with obs-fold.

> A recipient SHOULD treat other octets in field content (obs-text) as opaque data.

This is also not relevant to the issue you are seeing, because `\x01` is part of US-ASCII. guzzle/psr7 indeed accepts “other octets” (i.e. >= 128) as opaque data.

> [Comments in the source file](https://github.com/guzzle/psr7/blob/bc778a3f18eb0f8423ea707cd0bdf375c696ec81/src/MessageTrait.php#L254-L257) suggest confusion between Guzzle acting as a client vs as a sender.

Did you mean "server" instead of "sender"? Both communication partners are senders, because they both send messages (request and response respectively).

In any case: guzzle/psr7 is usable for both clients (user-agents) and servers. It also includes the PSR-7 ServerRequest implementation.

---------

Regarding the report [RFC 9110#5.5](https://httpwg.org/specs/rfc9110.html#rfc.section.5.5) says:

> Field values containing CR, LF, or NUL characters are invalid and dangerous, due to the varying ways that implementations might parse and interpret those characters; a recipient of CR, LF, or NUL within a field value MUST either reject the message or replace each of those characters with SP before further processing or forwarding of that message. Field values containing other CTL characters are also invalid; however, recipients MAY retain such characters for the sake of robustness when they appear within a safe context (e.g., an application-specific quoted string that will not be processed by any downstream HTTP parser).

In your case you are dealing with a CTL character, so:

> Field values containing other CTL characters are also invalid; however, recipients MAY retain such characters for the sake of robustness when they appear within a safe context (e.g., an application-specific quoted string that will not be processed by any downstream HTTP parser).

The `\x01` MAY be retained, but only if it is guaranteed that the downstream processing knows how to correctly deal with it. As guzzle/psr7 is a generic library that (a) does not know the semantics of the headers it parses (a CTL might be safe in a user-agent header, but unsafe in an authorization header) and (b) does not know what the downstream processors do with the values, it must err on the side of caution and reject those values.

see also: https://github.com/guzzle/psr7/issues/517#issuecomment-1154399091

You should message the vendor of your server to get them to fix their broken HTTP implementation.
